"""add_user_type_to_users

Revision ID: aa3fb43c50a6
Revises: 002_seed_products
Create Date: 2025-08-13 00:09:18.390537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa3fb43c50a6'
down_revision = '002_seed_products'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'cart_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('cart_items', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_index('uq_cart_product', table_name='cart_items')
    op.create_index('idx_cart_item_cart_product', 'cart_items', ['cart_id', 'product_id'], unique=True)
    op.create_index('idx_cart_item_product', 'cart_items', ['product_id'], unique=False)
    op.add_column('carts', sa.Column('cart_token', sa.String(length=255), nullable=True))
    op.alter_column('carts', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    op.alter_column('carts', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_cart_token', 'carts', ['cart_token'], unique=False)
    op.create_index('idx_cart_user', 'carts', ['user_id'], unique=False)
    op.create_index(op.f('ix_carts_cart_token'), 'carts', ['cart_token'], unique=False)
    op.drop_column('carts', 'guest_token')
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_order_item_order', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_item_product', 'order_items', ['product_id'], unique=False)
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'total_price')
    op.alter_column('orders', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_order_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('idx_order_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.drop_constraint('orders_ibfk_1', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('orders', 'billing_address')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'guest_email')
    op.add_column('payments', sa.Column('raw_payload', sa.JSON(), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.create_index('idx_payment_order', 'payments', ['order_id'], unique=False)
    op.create_index('idx_payment_provider_id', 'payments', ['provider', 'provider_payment_id'], unique=False)
    op.create_index('idx_payment_status', 'payments', ['status'], unique=False)
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'provider_data')
    op.alter_column('products', 'slide_image_urls',
               existing_type=mysql.JSON(),
               comment='Array of image URLs',
               existing_nullable=True)
    op.alter_column('products', 'expiry_duration_months',
               existing_type=mysql.INTEGER(),
               comment='Months until expiry',
               existing_nullable=True)
    op.alter_column('products', 'rank_of_product',
               existing_type=mysql.INTEGER(),
               comment='For sorting/priority',
               existing_nullable=False)
    op.alter_column('products', 'fragrance_family',
               existing_type=mysql.VARCHAR(length=50),
               comment='Oriental, Fresh, Floral, Woody, etc.',
               existing_nullable=True)
    op.alter_column('products', 'concentration',
               existing_type=mysql.VARCHAR(length=20),
               comment='EDT, EDP, Parfum, Cologne, etc.',
               existing_nullable=True)
    op.alter_column('products', 'volume_ml',
               existing_type=mysql.INTEGER(),
               comment='Volume in milliliters',
               existing_nullable=True)
    op.alter_column('products', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               comment='Men, Women, Unisex',
               existing_nullable=True)
    op.alter_column('products', 'top_notes',
               existing_type=mysql.JSON(),
               comment='Top fragrance notes',
               existing_nullable=True)
    op.alter_column('products', 'middle_notes',
               existing_type=mysql.JSON(),
               comment='Middle/heart fragrance notes',
               existing_nullable=True)
    op.alter_column('products', 'base_notes',
               existing_type=mysql.JSON(),
               comment='Base fragrance notes',
               existing_nullable=True)
    op.alter_column('products', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_index('slug', table_name='products')
    op.create_index(op.f('ix_products_fragrance_family'), 'products', ['fragrance_family'], unique=False)
    op.create_index(op.f('ix_products_quantity'), 'products', ['quantity'], unique=False)
    op.create_index(op.f('ix_products_rank_of_product'), 'products', ['rank_of_product'], unique=False)
    op.add_column('social_accounts', sa.Column('provider_account_id', sa.String(length=255), nullable=False))
    op.add_column('social_accounts', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('social_accounts', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.alter_column('social_accounts', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('social_accounts', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_index('uq_social_provider_user', table_name='social_accounts')
    op.create_index('idx_social_provider_account', 'social_accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_index('idx_social_user_provider', 'social_accounts', ['user_id', 'provider'], unique=True)
    op.drop_column('social_accounts', 'provider_data')
    op.drop_column('social_accounts', 'provider_user_id')
    op.drop_column('social_accounts', 'provider_email')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.Enum('ANONYMOUS', 'REGISTERED', 'SOCIAL', name='usertype'), nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_index('email', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('idx_user_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index('idx_user_last_login', 'users', ['last_login'], unique=False)
    op.create_index('idx_user_type', 'users', ['user_type'], unique=False)
    op.create_index('idx_user_type_active', 'users', ['user_type', 'is_active'], unique=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index('idx_user_type_active', table_name='users')
    op.drop_index('idx_user_type', table_name='users')
    op.drop_index('idx_user_last_login', table_name='users')
    op.drop_index('idx_user_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('email', 'users', ['email'], unique=False)
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'hashed_password')
    op.add_column('social_accounts', sa.Column('provider_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('social_accounts', sa.Column('provider_user_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('social_accounts', sa.Column('provider_data', mysql.JSON(), nullable=True))
    op.drop_index('idx_social_user_provider', table_name='social_accounts')
    op.drop_index('idx_social_provider_account', table_name='social_accounts')
    op.create_index('uq_social_provider_user', 'social_accounts', ['provider', 'provider_user_id'], unique=False)
    op.alter_column('social_accounts', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('social_accounts', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('social_accounts', 'refresh_token')
    op.drop_column('social_accounts', 'access_token')
    op.drop_column('social_accounts', 'provider_account_id')
    op.drop_index(op.f('ix_products_rank_of_product'), table_name='products')
    op.drop_index(op.f('ix_products_quantity'), table_name='products')
    op.drop_index(op.f('ix_products_fragrance_family'), table_name='products')
    op.create_index('slug', 'products', ['slug'], unique=False)
    op.alter_column('products', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('products', 'base_notes',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Base fragrance notes',
               existing_nullable=True)
    op.alter_column('products', 'middle_notes',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Middle/heart fragrance notes',
               existing_nullable=True)
    op.alter_column('products', 'top_notes',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Top fragrance notes',
               existing_nullable=True)
    op.alter_column('products', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='Men, Women, Unisex',
               existing_nullable=True)
    op.alter_column('products', 'volume_ml',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Volume in milliliters',
               existing_nullable=True)
    op.alter_column('products', 'concentration',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='EDT, EDP, Parfum, Cologne, etc.',
               existing_nullable=True)
    op.alter_column('products', 'fragrance_family',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Oriental, Fresh, Floral, Woody, etc.',
               existing_nullable=True)
    op.alter_column('products', 'rank_of_product',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='For sorting/priority',
               existing_nullable=False)
    op.alter_column('products', 'expiry_duration_months',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Months until expiry',
               existing_nullable=True)
    op.alter_column('products', 'slide_image_urls',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='Array of image URLs',
               existing_nullable=True)
    op.add_column('payments', sa.Column('provider_data', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'orders', ['order_id'], ['id'])
    op.drop_index('idx_payment_status', table_name='payments')
    op.drop_index('idx_payment_provider_id', table_name='payments')
    op.drop_index('idx_payment_order', table_name='payments')
    op.alter_column('payments', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('payments', 'raw_payload')
    op.add_column('orders', sa.Column('guest_email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', mysql.JSON(), nullable=True))
    op.add_column('orders', sa.Column('billing_address', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_ibfk_1', 'orders', 'users', ['user_id'], ['id'])
    op.drop_index('idx_order_user_status', table_name='orders')
    op.drop_index('idx_order_status_created', table_name='orders')
    op.alter_column('orders', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.add_column('order_items', sa.Column('total_price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index('idx_order_item_product', table_name='order_items')
    op.drop_index('idx_order_item_order', table_name='order_items')
    op.alter_column('order_items', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.add_column('carts', sa.Column('guest_token', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_carts_cart_token'), table_name='carts')
    op.drop_index('idx_cart_user', table_name='carts')
    op.drop_index('idx_cart_token', table_name='carts')
    op.alter_column('carts', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('carts', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.drop_column('carts', 'cart_token')
    op.drop_index('idx_cart_item_product', table_name='cart_items')
    op.drop_index('idx_cart_item_cart_product', table_name='cart_items')
    op.create_index('uq_cart_product', 'cart_items', ['cart_id', 'product_id'], unique=False)
    op.alter_column('cart_items', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('cart_items', 'cart_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###